version: '3'
services:
  client-remote:
    image: node:16
    container_name: client-remote
    working_dir: /home/client
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./client:/home/client
  api-remote:
    image: node:16
    container_name: api-remote
    working_dir: /home/api
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./api:/home/api